version: '3'
services:
  labnine:
    build: .
    container_name: labapp
    ports:
      - "8080:8080"
    depends_on:
      - labninesql
    networks:
      - lsn

  labninesql:
    image: mysql:latest
    container_name: labsql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    networks:
      - lsn


networks:
  lsn:
    external: true	
