version: "3.8"

services:
   db:
       image: mysql:latest
       environment:
               DATABASE_HOST: docker-mysql
               DATABASE_PORT: 3306
               MYSQL_ROOT_PASSWORD: 2102
               MYSQL_DATABASE: hibernateDB
               MYSQL_USER: dbuser
               MYSQL_PASSWORD: hello@123
       networks:
        - default
   app:
       image: studentel:latest
       ports: 
       - 8080:8080
       environment:
              spring.datasource.url: jdbc:mysql://db:3306/hibernateDB
              spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
              spring.datasource.username: dbuser
              spring.datasource.password: hello@123
       depends_on: 
            - db
       networks:
            - default
